name: Conventional-Commits

on:
  workflow_call:
    secrets:
      GITHUB_TOKEN:
        required: true

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          validateSingleCommit: true
          wip: true
  single-commit:
    name: Ensure Single Commit 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/single-commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}