name: Pre-commit auto-update

on:
  workflow_call:
    secrets:
      TERRAFORM_MODULES_ROLE_ARN:
        required: true
      TERRAFORM_MODULES_REGION:
        required: true

jobs:
  auto-update:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.TERRAFORM_MODULES_ROLE_ARN }}
          aws-region: ${{ secrets.TERRAFORM_MODULES_REGION }}
      - uses: actions/checkout@v2
      
      - uses: actions/setup-python@v2
      
      - run: pip install pre-commit
        shell: bash
      - name: install pre-commit dependencies
        run: |
          pip install pre-commit
          curl -Lo ./terraform-docs.tar.gz https://github.com/terraform-docs/terraform-docs/releases/download/v0.16.0/terraform-docs-v0.16.0-$(uname)-amd64.tar.gz && tar -xzf terraform-docs.tar.gz terraform-docs && chmod +x terraform-docs && sudo mv terraform-docs /usr/bin/ && rm terraform-docs.tar.gz
          curl -L "$(curl -s https://api.github.com/repos/terraform-linters/tflint/releases/latest | grep -o -E "https://.+?_linux_amd64.zip")" > tflint.zip && unzip tflint.zip && rm tflint.zip && sudo mv tflint /usr/bin/
      - run: pre-commit autoupdate
        shell: bash
      - run: pre-commit run --all-files
        shell: bash
      - uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update/pre-commit-hooks
          title: Update pre-commit hooks
          commit-message: "chore: update pre-commit hooks"
          body: Update versions of pre-commit hooks to latest version.
