name: Release and push
on:
  workflow_call:
    inputs:
      aws-role-to-assume:
        required: true
        type: string
      aws-region:
        required: true
        type: string

jobs:
  bump:
    runs-on: ubuntu-latest
    # Needed to interact with Github's OIDC token
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ inputs.aws-role-to-assume }}
          aws-region: ${{ inputs.aws-region }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-on-empty: 'false'
          skip-version-file: 'true'
          release-count: '1'
      - name: Mirror in S3
        run: make s3
        env:
          TAG: ${{ steps.changelog.outputs.tag }}
      - name: Create Release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}