name: Terraform-Observe Test Scheduler

on:
  workflow_call:
    inputs:
      skip:
        required: false
        type: string
        description: "example: {\"jobs\": [\"validate-pr-title\", \"single-commit\"]}"

jobs:
  conventional-commits:
    if: "!contains(fromJSON(inputs.skip).jobs, 'conventional-commits')"
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          validateSingleCommit: true
          wip: true

  single-commit:
    if: "!contains(fromJSON(inputs.skip).jobs, 'single-commit')"
    name: Ensure Single Commit 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: observeinc/terraform-observe-ci-tests/.github/actions/single-commit@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ci-tests:
    if: "!contains(fromJSON(inputs.skip).jobs, 'ci-tests')"
    name: CI Tests Placeholder
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run CI Tests Checks
        uses: observeinc/terraform-observe-ci-tests/.github/actions/ci-tests@main
        with:
          skip: ${{ inputs.skip }}
          token: ${{ secrets.GITHUB_TOKEN }}
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
