name: Shared Commit Validation

on:
  workflow_call:
    inputs:
      skip:
        required: false
        type: string
        description: "example: {\"jobs\": [\"validate-pr-title\", \"single-commit\"]}"

jobs:
  conventional-commits:
    permissions: write-all
    if: "github.event_name == 'pull_request' && !contains(fromJSON(inputs.skip).jobs, 'conventional-commits')"
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          validateSingleCommit: true
          wip: true

  single-commit:
    if: "github.event_name == 'pull_request' && !contains(fromJSON(inputs.skip).jobs, 'single-commit')"
    name: Ensure Single Commit 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: observeinc/.github/.github/actions/shared/single-commit@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
