name: Publish prerelease
on:
  workflow_call:
    secrets:
      TERRAFORM_MODULES_ROLE_ARN:
        required: true
      TERRAFORM_MODULES_REGION:
        required: true
      TERRAFORM_MODULES_SLACK_URL:
        required: false

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.TERRAFORM_MODULES_ROLE_ARN }}
          aws-region: ${{ secrets.TERRAFORM_MODULES_REGION }}
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Mirror in S3
        run: make s3
      - name: Prepare Slack notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.TERRAFORM_MODULES_SLACK_URL }}
        if: ${{ env.SLACK_WEBHOOK_URL != '' }}
        run: |
          echo version=$(git describe --tags --always | sed 's/^v//' ) >> $GITHUB_ENV
          echo name=$(echo "$GITHUB_REPOSITORY" | sed 's/^.*terraform-observe-//') >> $GITHUB_ENV
      - name: Notify Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.TERRAFORM_MODULES_SLACK_URL }}
        if: ${{ env.SLACK_WEBHOOK_URL != '' }}
        uses: slackapi/slack-github-action@v1.19.0
        with:
          payload: |
            {
              "namespace": "observeinc",
              "name": "${{ env.name }}",
              "system": "observe",
              "version": "${{ env.version }}",
              "repo": "${{ github.repository }}",
              "commit_link": "https://github.com/${{ github.repository }}/tree/${{ github.sha }}"
            }
