name: Terraform-Observe Test Scheduler

on:
  workflow_call:
    inputs:
      skip:
        required: false
        type: string
        description: "example: {\"jobs\": [\"validate-pr-title\", \"single-commit\"]}"

jobs:
  commit-validation:
    uses: ./.github/workflows/shared_commit-validation.yaml
    secrets: inherit
    with:
      skip: ${{ inputs.skip }}

  find-modules:
    runs-on: ubuntu-latest
    steps:
      - id: find
        uses: bendrucker/find-terraform-modules@v1
        with:
          working-directory: ./tftests
    outputs:
      modules: ${{ steps.find.outputs.modules }}
  terraform-test-apply:
    name: Test Terraform Module
    needs: find-modules
    if: ${{ needs.find-modules.outputs.directories != '[]' && needs.find-modules.outputs.directories != '' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module: ${{ fromJson(needs.find-modules.outputs.modules) }}
    steps:
      - uses: hashicorp/setup-terraform@v2
        with: 
          terraform_version: 1.2.9
      - uses: actions/checkout@v2
      - name: make test
        run: make test "${{ matrix.module }}"
        env:
          OBSERVE_CUSTOMER: ${{ secrets.TERRAFORM_MODULES_TEST_OBSERVE_CUSTOMER }}
          OBSERVE_DOMAIN: ${{ secrets.TERRAFORM_MODULES_TEST_OBSERVE_DOMAIN }}
          OBSERVE_USER_EMAIL: ${{ secrets.TERRAFORM_MODULES_TEST_OBSERVE_USER_EMAIL }}
          OBSERVE_USER_PASSWORD: ${{ secrets.TERRAFORM_MODULES_TEST_OBSERVE_USER_PASSWORD }}
          
          GITHUB_WORKSPACE: ${{ github.workspace }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ci-tests:
    if: "!contains(fromJSON(inputs.skip).jobs, 'ci-tests')"
    name: CI Tests Placeholder
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run CI Tests Checks
        uses: observeinc/.github/.github/actions/terraform-observe/ci-tests@main
        with:
          skip: ${{ inputs.skip }}
          token: ${{ secrets.GITHUB_TOKEN }}
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
