name: Terraform-Observe Test Scheduler

on:
  workflow_call:
    inputs:
      skip:
        required: false
        type: string
        description: 'example: {"jobs": ["validate-pr-title", "single-commit"]}'
      terraform-version:
        description: "Terraform version"
        required: false
        type: string
        default: "latest"

jobs:
  commit-validation:
    uses: ./.github/workflows/shared_commit-validation.yaml
    secrets: inherit
    with:
      skip: ${{ inputs.skip }}

  get-test-directories:
    if: "!contains(fromJSON(inputs.skip).jobs, 'terraform-tests')"
    name: Get Terraform Test Directories
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build matrix
        id: matrix
        shell: bash
        run: |
          DIRS="$(find . -path "*tftests/*" ! -path "*.terraform*" -type d )"
          [[ ${#DIRS} > 0 ]] && echo "directories=[\"${DIRS//$'\n'/\",\"}\"]" >> "$GITHUB_OUTPUT" || echo "directories=[]" >> "$GITHUB_OUTPUT"
    outputs:
      directories: ${{ steps.matrix.outputs.directories }}

  terraform-test-apply:
    needs: get-test-directories
    if: ${{ needs.get-test-directories.outputs.directories != '[]' && needs.get-test-directories.outputs.directories != '' }}
    name: Test Terraform Module
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        directory: ${{ fromJson(needs.get-test-directories.outputs.directories) }}
    steps:
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ inputs.terraform-version }}
      - uses: actions/checkout@v4
      - name: make test
        run: make test "${{ matrix.directory }}"
        env:
          OBSERVE_CUSTOMER: ${{ secrets.TERRAFORM_MODULES_TEST_OBSERVE_CUSTOMER }}
          OBSERVE_DOMAIN: ${{ secrets.TERRAFORM_MODULES_TEST_OBSERVE_DOMAIN }}
          OBSERVE_USER_EMAIL: ${{ secrets.TERRAFORM_MODULES_TEST_OBSERVE_USER_EMAIL }}
          OBSERVE_USER_PASSWORD: ${{ secrets.TERRAFORM_MODULES_TEST_OBSERVE_USER_PASSWORD }}

          GITHUB_WORKSPACE: ${{ github.workspace }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Validate App Icon URL is internal
  validate-app-icon:
    name: Validate App Icon
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Check manifest.yaml exists
        id: check_manifest
        uses: andstor/file-existence-action@v3
        with:
          files: "manifest.yaml"
      - name: Get App Icon URL
        id: get_icon_url
        uses: mikefarah/yq@v4.42.1
        if: steps.check_manifest.outputs.files_exists == 'true'
        with:
          cmd: yq 'with_entries(.key |= downcase).iconurl' manifest.yaml
      - name: Validate App Icon URL Is Internal
        if: ${{ !startsWith(steps.get_icon_url.outputs.result, 'https://assets.observeinc.com/') && steps.check_manifest.outputs.files_exists == 'true' }}
        run: echo "::error file=manifest.yaml,title=Invalid App Icon URL::App icon URLs must live in the 'assets.observeinc.com' domain" && exit 1
      - name: Validate App Icon URL Is Working
        uses: filiph/linkcheck@3.0.0
        if: steps.check_manifest.outputs.files_exists == 'true'
        with:
          arguments: ${{ steps.get_icon_url.outputs.result }}
